nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: ".yarn/releases/yarn-berry.js"

# Use this server when consuming artifacts
npmRegistryServer: "https://nexus.maindrain.net/repository/npm/"

# Use this server when publish artifacts
#npmRegistryServer: "https://nexus.maindrain.net/repository/npm-releases/"

npmScopes:
  openremote:
    npmRegistryServer: "https://nexus.maindrain.net/repository/npm-releases/"
    npmAuthIdent: "richturner:V4emdGxRUX9XvbkVWu6j"
