org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g
org.gradle.parallel=true

projectName = custom-project
version = 1.0-SNAPSHOT

# When updating the OpenRemote version, also update the version in gradle/libs.versions.toml
openremoteVersion = 1.26.2

ideaExtPluginVersion = 1.4.1
typescriptGeneratorVersion = 4.1.1
