plugins {
    id 'java-library'
}

dependencies {
    api project(":agent")
    api project(":model")
    api project(":manager")

    implementation libs.openremote.ui.insights
    implementation libs.openremote.ui.manager
    implementation libs.openremote.ui.shared
    implementation libs.openremote.ui.swagger
}

tasks.register('installDist') {
    dependsOn jar
}
