name: Run Spock Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Updated to the latest version
      - name: Set up JDK 17
        uses: actions/setup-java@v3 # Updated to the latest version
        with:
          java-version: '17'
          distribution: 'temurin' # Specify the distribution
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew test --info
